stages:
  - test
  - build

test_backend:
  stage: test
  image: node:22

  services:
    - name: postgres:16
      alias: postgres

  variables:
    # PostgreSQL
    POSTGRES_DB: pca_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

    # Variáveis da aplicação
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_NAME: pca_test

    PORT: "3000"

    NODE_ENV: test

    JWT_USER_SECRET: teste-user
    JWT_ADMIN_SECRET: teste-admin

    FRONTEND_URL: http://localhost:3000

    ADMIN_PASSWORD: admin123
    ADMIN_CPF: "11111111111"

  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h postgres -U postgres; do sleep 2; done
    - cd backend-pca
    - npm ci

  script:
    - npm test

build_backend:
  stage: build
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  needs:
    - test_backend

  script:
    - docker build -t backend-pca ./backend-pca

build_frontend:
  stage: build
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  needs:
    - test_backend

  script:
    - docker build -t frontend-pca ./frontend-pca