stages:
  - lint
  - security
  - test
  - build

# Configuração global de cache para não baixar a internet a cada job
cache:
  key:
    files:
      - backend-pca/package-lock.json
  paths:
    - backend-pca/.npm/
  policy: pull-push

lint_backend:
  stage: lint
  image: node:22
  before_script:
    - cd backend-pca
    # O --cache .npm faz o npm usar a pasta que salvamos no cache do GitLab
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint

security_audit:
  stage: security
  image: node:22

  needs:
    - lint_backend

  before_script:
    - cd backend-pca
    - npm ci --cache .npm --prefer-offline

  script:
    - npm audit --audit-level=high

secret_scan:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]

  needs:
    - lint_backend

  script:
    - gitleaks detect --source . --config .gitleaks.toml --verbose
    
sast_scan:
  stage: security
  image:
    name: returntocorp/semgrep:latest
    entrypoint: [""]

  needs:
    - lint_backend

  script:
    - semgrep scan --config=auto backend-pca

test_backend:
  stage: test
  image: node:22

  services:
    - name: postgres:16
      alias: postgres

  variables:
    # PostgreSQL
    POSTGRES_DB: pca_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

    # Variáveis da aplicação
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_NAME: pca_test
    PORT: "3000"
    NODE_ENV: test
    JWT_USER_SECRET: teste-user
    JWT_ADMIN_SECRET: teste-admin
    FRONTEND_URL: http://localhost:3000
    ADMIN_PASSWORD: admin123
    ADMIN_CPF: "11111111111"

  # Só começa a rodar o banco e os testes se o Lint passar
  needs:
    - lint_backend
    - security_audit
    - secret_scan
    - sast_scan

  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h postgres -U postgres; do sleep 2; done
    - cd backend-pca
    - npm ci --cache .npm --prefer-offline

  script:
    - npm audit --audit-level=high
    - npm test

build_backend:
  stage: build
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  needs:
    - test_backend

  script:
    - docker build -t backend-pca ./backend-pca

build_frontend:
  stage: build
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  needs:
    - test_backend

  script:
    - docker build -t frontend-pca ./frontend-pca